[workspace]
resolver = "2"
members = [
    "archk",
    "archk-api",
    "archk-api-docgen",
    "archk-api-server",
    "documentation-macro",
]
default-members = ["archk-api-server"]

[profile.release]
lto = true
strip = true
