[package]
name = "archk-api-docgen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
serde_json = "1"
clap = { version = "4.5", features = ["derive"] }

archk = { path = "../archk" }
archk-api = { path = "../archk-api" }
